on: [push, pull_request]
name: Analysis
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: fmt
      run: (! gofmt -d . | grep '^')
  vet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13.x
    - name: vet
      run: go vet ./...
